### ISSUE TITLE
Support multiple page counters

### ISSUE THREAD

**Issue by bertfrees** [braillespecs/braille-css#47]
Currently there exists a special `page` counter:

> A 'page' counter is created automatically on the root element. Its purpose is for numbering braille pages. The counter is implicitly incremented on each page. Depending on the implementation, explicitly setting or incrementing this counter may or may not have an effect. No new counters can be created with the name 'page'.

(see [Creating and inheriting counters](http://braillespecs.github.io/braille-css/#h4_creating-and-inheriting-counters))

With the latest OBFL addition, [`page-number-counter`](http://braillespecs.github.io/obfl/obfl-specification.html#pagenumbercounter), we could now support custom page counters.

Any counter that is manipulated in the page context would be a page counter. The counter named `page` would still be a special case in the sense that the default value of `counter-increment` inside the page context is `page`. However it would now become possible to overwrite this rule:

```css
@page {
    counter-increment: my-page;
}
```

You can also set instead of increment:

```css
@page {
    counter-set: my-page 3;
}
```

It is not allowed to have a more than one page counter on the same page (e.g. `counter-increment: page my-page`). Having no page counter (`counter-increment: none`) could in theory be allowed. It is not allowed to access or set the value of a page counter if it is not the page counter that is active on the current page.

The current behavior of the beginning and end sections of volumes could be accomplished with these implicit rules:

```css
@volume {
    @begin
        @page {
            counter-set: pre-page 1;
        }
    }
    @end
        @page {
            counter-set: post-page 1;
        }
    }
}
```
